# Generated by Django 3.0.8 on 2020-08-11 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0003_auto_20200811_1022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='tags',
        ),
    ]
