# Generated by Django 3.0.8 on 2020-08-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM_app', '0004_auto_20200811_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categort',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
